// AUTH TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_CONFIRM = 'REGISTER_CONFIRM';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const BEGIN_USER_LOAD = 'BEGIN_USER_LOAD';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// FILE TYPES
export const BEGIN_FILE_UPLOAD = 'BEGIN_FILE_UPLOAD';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_FAILURE = 'FILE_UPLOAD_FAILURE';
